# WBEMフラグ。関数により適不適が変わるため、定数として定義します。

# WBEM_CHANGE_FLAG_TYPE
WBEM_FLAG_CREATE_OR_UPDATE = 0
WBEM_FLAG_UPDATE_ONLY = 0x1
WBEM_FLAG_CREATE_ONLY = 0x2
WBEM_FLAG_UPDATE_COMPATIBLE = 0x0
WBEM_FLAG_UPDATE_SAFE_MODE = 0x20
WBEM_FLAG_UPDATE_FORCE_MODE = 0x40
WBEM_MASK_UPDATE_MODE = 0x60

WBEM_FLAG_ADVISORY = 0x000010000

# tag_WBEM_GENERIC_FLAG_TYPE
WBEM_FLAG_RETURN_IMMEDIATELY = 0x10
WBEM_FLAG_RETURN_WBEM_COMPLETE = 0
WBEM_FLAG_BIDIRECTIONAL = 0
WBEM_FLAG_FORWARD_ONLY = 0x20
WBEM_FLAG_NO_ERROR_OBJECT = 0x40
WBEM_FLAG_RETURN_ERROR_OBJECT = 0
WBEM_FLAG_SEND_STATUS = 0x80
WBEM_FLAG_DONT_SEND_STATUS = 0
WBEM_FLAG_ENSURE_LOCATABLE = 0x100
WBEM_FLAG_DIRECT_READ = 0x200
WBEM_FLAG_SEND_ONLY_SELECTED = 0

WBEM_RETURN_WHEN_COMPLETE = 0
"""後方互換性用。通常は使用しません。"""
WBEM_RETURN_IMMEDIATELY = 0x10
"""後方互換性用。通常は使用しません。"""

WBEM_MASK_RESERVED_FLAGS = 0x1F000
"""予約フラグ。通常は使用しません。"""

WBEM_FLAG_USE_AMENDED_QUALIFIERS = 0x20000
WBEM_FLAG_STRONG_VALIDATION = 0x100000

# WBEM_CONDITION_FLAG_TYPE
WBEM_FLAG_ALWAYS = 0
WBEM_FLAG_ONLY_IF_TRUE = 0x1
WBEM_FLAG_ONLY_IF_FALSE = 0x2
WBEM_FLAG_ONLY_IF_IDENTICAL = 0x3
WBEM_MASK_PRIMARY_CONDITION = 0x3
WBEM_FLAG_KEYS_ONLY = 0x4
WBEM_FLAG_REFS_ONLY = 0x8
WBEM_FLAG_LOCAL_ONLY = 0x10
WBEM_FLAG_PROPAGATED_ONLY = 0x20
WBEM_FLAG_SYSTEM_ONLY = 0x30
WBEM_FLAG_NONSYSTEM_ONLY = 0x40
WBEM_MASK_CONDITION_ORIGIN = 0x70
WBEM_FLAG_CLASS_OVERRIDES_ONLY = 0x100
WBEM_FLAG_CLASS_LOCAL_AND_OVERRIDES = 0x200
WBEM_MASK_CLASS_CONDITION = 0x300

# WBEM_QUERY_FLAG_TYPE
WBEM_FLAG_DEEP = 0
WBEM_FLAG_SHALLOW = 1
WBEM_FLAG_PROTOTYPE = 2

# WBEM_SECURITY_FLAGS
WBEM_ENABLE = 1
WBEM_METHOD_EXECUTE = 2
WBEM_FULL_WRITE_REP = 4
WBEM_PARTIAL_WRITE_REP = 8
WBEM_WRITE_PROVIDER = 0x10
WBEM_REMOTE_ACCESS = 0x20
WBEM_RIGHT_SUBSCRIBE = 0x40
WBEM_RIGHT_PUBLISH = 0x80

# WBEM_LIMITATION_FLAG_TYPE
WBEM_FLAG_EXCLUDE_OBJECT_QUALIFIERS = 0x10
WBEM_FLAG_EXCLUDE_PROPERTY_QUALIFIERS = 0x20

# WBEM_TEXT_FLAG_TYPE
WBEM_FLAG_NO_FLAVORS = 0x1

# WBEM_COMPARISON_FLAG
WBEM_COMPARISON_INCLUDE_ALL = 0
WBEM_FLAG_IGNORE_QUALIFIERS = 0x1
WBEM_FLAG_IGNORE_OBJECT_SOURCE = 0x2
WBEM_FLAG_IGNORE_DEFAULT_VALUES = 0x4
WBEM_FLAG_IGNORE_CLASS = 0x8
WBEM_FLAG_IGNORE_CASE = 0x10
WBEM_FLAG_IGNORE_FLAVOR = 0x20

# WBEM_LOCKING
WBEM_FLAG_ALLOW_READ = 0x1

# WBEM_BACKUP_RESTORE_FLAGS
WBEM_FLAG_BACKUP_RESTORE_DEFAULT = 0
WBEM_FLAG_BACKUP_RESTORE_FORCE_SHUTDOWN = 1

# WBEM_REFRESHER_FLAGS
WBEM_FLAG_REFRESH_AUTO_RECONNECT = 0
WBEM_FLAG_REFRESH_NO_AUTO_RECONNECT = 1

# WBEM_SHUTDOWN_FLAGS
WBEM_SHUTDOWN_UNLOAD_COMPONENT = 1
WBEM_SHUTDOWN_WMI = 2
WBEM_SHUTDOWN_OS = 3


# WBEM_COMPILER_OPTIONS
WBEM_FLAG_CHECK_ONLY = 0x1
WBEM_FLAG_AUTORECOVER = 0x2
WBEM_FLAG_WMI_CHECK = 0x4
WBEM_FLAG_CONSOLE_PRINT = 0x8
WBEM_FLAG_DONT_ADD_TO_LIST = 0x10
WBEM_FLAG_SPLIT_FILES = 0x20
WBEM_FLAG_STORE_FILE = 0x100

# WBEM_CONNECT_OPTIONS
WBEM_FLAG_CONNECT_REPOSITORY_ONLY = 0x40
WBEM_FLAG_CONNECT_USE_MAX_WAIT = 0x80
WBEM_FLAG_CONNECT_PROVIDERS = 0x100

# WBEM_UNSECAPP_FLAG_TYPE
WBEM_FLAG_UNSECAPP_DEFAULT_CHECK_ACCESS = 0
WBEM_FLAG_UNSECAPP_CHECK_ACCESS = 1
WBEM_FLAG_UNSECAPP_DONT_CHECK_ACCESS = 2

# WBEM_INFORMATION_FLAG_TYPE
WBEM_FLAG_SHORT_NAME = 0x1
WBEM_FLAG_LONG_NAME = 0x2

# WBEM_PROVIDER_FLAGS
WBEM_FLAG_OWNER_UPDATE = 0x10000
